### ISSUE TITLE
[BUG] Error from missing taxonomy term for fits derivative

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora/islandora-starter-site#13]
I get the following error when attempting to add a PDF `original file` media entity to a `Digital Document` object.

```
Error message
Error generating event: Could not locate taxonomy term with uri: https://projects.iq.harvard.edu/fits
```

Seems to stem from the derivative action making a reference to a taxonomy term that does not exist. See the config references [here](https://github.com/Islandora/islandora-starter-site/blob/0d07ddb01e4ba6394bb3891b0d231bc2eff753f9/config/sync/system.action.generate_a_technical_metadata_derivative.yml#L20).

Seems like this entry should be added to the migration tags, [here](https://github.com/Islandora/islandora-starter-site/blob/0d07ddb01e4ba6394bb3891b0d231bc2eff753f9/assets/migrate/tags.csv)? Though it looks like the intention is to handle it in the module from this [pull request](https://github.com/roblib/islandora_fits/pull/14). The read me seem to reflect [this](https://github.com/Islandora/islandora-starter-site/blob/main/README.md#assetspatchesislandora_fitsmigrate_term_and_squash_configdiff). So perhaps the read me & composer files need updating?

**Comment by rosiel** [comment]
nice catch!

**Comment by nigelgbanks** [comment]
Oh, I just was setting it up more or less manually in my little test repo here: https://github.com/nigelgbanks/starter-site-test, as I wanted to use it isolated from the other two (eventually sandbox will be based off it, and it doesn't use `isle-dc` or the `islandora-playbook` there are quite a few installations out there that just roll their own as well). You're most likely right that it's just missing from the read me, I'll test tomorrow.

**Comment by adam-vessey** [comment]
@nigelgbanks: With #14 having been merged, can this issue now be closed?

**Comment by nigelgbanks** [comment]
> @nigelgbanks: With #14 having been merged, can this issue now be closed?

Whoops yup 👍
