### ISSUE TITLE
Replace islandora_defaults with an exported site islandora-starter-site

### ISSUE THREAD

**Issue by lutaylor** [Islandora/islandora-starter-site#2]
**Overview**

Intial work to replace https://github.com/Islandora/islandora_defaults with an exported site in a project housed in this repository  https://github.com/Islandora/islandora-starter-site/. 

The intent is to simplify expectations and maintenance. This is to help facilitate the communities end goal to modularize Islandora into largely independent Drupal modules that let Drupal sites pick and choose their repository features. 

The structure of the example site could look like:

https://github.com/Islandora/islandora-starter-site/

-composer.json / composer.lock
-config/sync
-content/sync

**Acceptance Criteria** 
-We have an islandora_defaults replacement exported starter site.  
-Current enabled islandora_default functionality as installed with the Islandora Playbook in Olivero is present. 
-README should contain instructions on how to manually utilize the starter-site outside of ISLE/playbook. README should specify awareness for existing sites.

**Out of Scope**
Removing islandora_defaults from existing sites

**Reference**
https://docs.google.com/document/d/1fx8PvSpft8c3OPMLrN5SjaqOhcHOuRr_xjgqnBe8gg4/edit#heading=h.w3w654y9wz7s

**Contacts**
On Islandora slack
Rosie Le Faive (Product owner)
Luke Taylor (Project Manager)

**Comment by adam-vessey** [comment]
Just a note: Work had been started at the [presently-latest release of 2.1.1 of `islandora_defaults`](https://github.com/Islandora/islandora_defaults/releases/tag/2.1.1)... Looking at the diff between it and the present unreleased `HEAD` of [`7b34ad2`](https://github.com/Islandora/islandora_defaults/commit/7b34ad289402698c1403361155f242cb32e18a0d): https://github.com/Islandora/islandora_defaults/compare/2.1.1...7b34ad2 ... is fairly small stuff, pretty much:

* The Drupal version compatibility assertions (dropping 8)
* The `resources_types` URI change for the "Collection" term; and,
* The changing of the condition plugin in the `repository_content` context

... Notably, don't presently have an analog for existing action/CI workflow, as it has the project baked in and the like, which would require some reworking to use with this starter site approach.

**Comment by adam-vessey** [comment]
Looks like I had already had the "Collection" term URI updated (slight goof in workflow having made it easier to grab the file from Github... which resulted in me grabbing it from `islandora_defaults`'s `HEAD`, instead of from the 2.1.1 release).

Otherwise, effected the other two changes between https://github.com/Islandora/islandora-starter-site/pull/1/files/e4ef87debd5a755d01172cdb12dcc57e585c8d3c..4f94206d456f54c8fafc55275d2b425599f5b962

**Comment by rosiel** [comment]
The replacement for Defaults has been completed.
